require_relative './config/environment'

# import all the rake tasks from ActiveRecord
require 'sinatra/activerecord/rake'

desc 'Starts an interactive session with out app'
task :console do
    binding.pry
end

desc 'Prints out hello to the terminal'
task :hello do
    puts "hello!"
end

desc 'Executes a different task'
task :task2 do
    puts "I am task two!"
end

desc 'Runs out bin/run.rb program'
task :run do
    MyMain.run
end